export { InHouseBanner } from './components/InHouseBanner/InHouseBanner'
export { InHouseCard } from './components/InHouseCard/InHouseCard'
export { ListaDeProgramas } from './components/ListaDeProgramas/ListaDeProgramas'
export { MyButtons } from './components/MyButtons/MyButtons'
export { AcercaDeNosotros } from './components/AcercaDeNosotros/AcercaDeNosotros'
export { BeneficiosDeLa } from './components/BeneficiosDeLa/BeneficiosDeLa'
export { LastBlock } from './components/LastBlock/LastBlock'
export { Cotizacion } from './components/Cotizacion/Cotizacion'
