export { BeneficiosDeNuestrosProgramas } from './components/BeneficiosDeNuestrosProgramas/BeneficiosDeNuestrosProgramas'
export { Carosuel } from './components/Carosuel/Carosuel'
export { CentroDeCapacitacion } from './components/CentroDeCapacitacion/CentroDeCapacitacion'
export { CertificiacionIso } from './components/CertificiacionIso/CertificiacionIso'
export { EstamosEnLinea } from './components/EstamosEnLinea/EstamosEnLinea'
export { TheMsg } from './components/TheMsg/TheMsg'
export { MobCart } from './components/MobCart/MobCart'
export { MobNoti } from './components/MobNoti/MobNoti'
